"use client";

import { useState } from "react";
import { Sparkles, FileText, Loader2, RefreshCw, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTeam } from "@/hooks/use-team";

interface WeeklyReportProps {
  analyticsData: {
    totalClicks: number;
    topLinks: { slug: string; title?: string | null; count: number }[];
    topCountries: { country: string; count: number }[];
    deviceSplit: { device_type: string; count: number }[];
    topReferrers: { domain: string; count: number }[];
    dailyTrend: { date: string; count: number }[];
  };
}

export function WeeklyReport({ analyticsData }: WeeklyReportProps) {
  const [report, setReport] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const { activeTeam } = useTeam();

  const generateReport = async () => {
    setLoading(true);
    setExpanded(true);
    try {
      const res = await fetch("/api/ai/weekly-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ teamId: activeTeam?.id, analyticsData }),
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();
      setReport(data.report || "No report generated.");
    } catch {
      setReport("Could not generate report. Make sure your `GROQ_API_KEY` is set in `.env.local`.");
    } finally {
      setLoading(false);
    }
  };

  const renderMarkdown = (text: string) =>
    text
      .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white">$1</strong>')
      .replace(/^### (.*)/gm, '<h3 class="text-sm font-black text-[#00D26A] uppercase tracking-widest mt-4 mb-1">$1</h3>')
      .replace(/^## (.*)/gm, '<h2 class="text-base font-black text-white mt-5 mb-2">$1</h2>')
      .replace(/^- (.*)/gm, '<li class="flex gap-2 text-sm"><span class="text-[#00D26A] shrink-0">›</span><span>$1</span></li>')
      .replace(/(<li.*<\/li>\n?)+/g, '<ul class="space-y-1 my-2 ml-1">$&</ul>')
      .replace(/\n\n/g, '<br/><br/>')
      .replace(/\n/g, '<br/>');

  return (
    <div className="glass-card rounded-2xl overflow-hidden">
      <div
        className="flex items-center justify-between p-5 cursor-pointer select-none"
        onClick={() => report && setExpanded(!expanded)}
      >
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-[#00D26A]/10 text-[#00D26A]">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <p className="text-sm font-black text-white">AI Weekly Intelligence Report</p>
            <p className="text-[10px] text-neutral-500">
              Auto-generated narrative analysis · Updated on demand
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            onClick={(e) => { e.stopPropagation(); generateReport(); }}
            disabled={loading}
            size="sm"
            className="h-8 text-[10px] font-black uppercase tracking-widest btn-primary-pulse"
          >
            {loading ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" />
            ) : report ? (
              <RefreshCw className="w-3.5 h-3.5 mr-1" />
            ) : (
              <FileText className="w-3.5 h-3.5 mr-1" />
            )}
            {loading ? "Generating..." : report ? "Regenerate" : "Generate"}
          </Button>
          {report && (
            <button className="text-neutral-500 hover:text-white transition-colors">
              {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
            </button>
          )}
        </div>
      </div>

      {expanded && report && (
        <div className="px-5 pb-5 border-t border-white/5 pt-4">
          <div
            className="text-sm text-neutral-400 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(report) }}
          />
          <p className="text-[10px] text-neutral-600 mt-4">
            Generated by Llama 3.3 70B via Groq · Based on last 7 days of analytics
          </p>
        </div>
      )}
    </div>
  );
}
