ALTER TABLE public.collections
  ADD COLUMN IF NOT EXISTS is_starred BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_rotator BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS rotator_slug TEXT UNIQUE;
